<a href="https://colab.research.google.com/github/amornvitz/HCIA-AI/blob/main/HCIA_AI_Day1_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy = Numerical Python
NumPy is a python library used for working with arrays.
It also has functions for working in domain of linear algebra, fourier transform, and matrices.
NumPy aims to provide an array object that is up to 50x faster that traditional Python lists.
NumPy is a Python library and is written partially in Python, but most of the parts that require fast computation are written in C or C++.

In [1]:
# Import Numpy in your application
import numpy as np
# Create 1-D array
ar0=np.array([100])
ar=np.array([1,2,3,4,5,6,7,8,9])
print(ar)
print(ar0)
# NumPy is used to work with arrays. The array object in NumPy is called ndarray.
print(type(ar))
# Check version
print(np.__version__)

[1 2 3 4 5 6 7 8 9]
[100]
<class 'numpy.ndarray'>
1.18.5


In [2]:
# Create multi-dimensional arrays
ar2=np.array([[1,2,3],[4,5,6]])
print(ar2)
ar3=np.array([[1,2],[3,4],[5,6]])
print(ar3)
ar3i=np.array([[1],[2],[3],[4],[5]])
print(ar3i)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
[[1]
 [2]
 [3]
 [4]
 [5]]


In [3]:
# Check for the number of dimensions the arrays have
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
e = np.array([[[10,11],[20,21]],[[30,31],[40,41]],[[50,51],[60,61]]])
f = np.array([[[10,11],[20,21],[30,31]],[[40,41],[50,51],[60,61]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)
print(e.ndim)
print(f.ndim)
print(b)
print(c)
print(d)
print(e)
print(np.__version__)
print(f)

0
1
2
3
3
3
[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
[[[10 11]
  [20 21]]

 [[30 31]
  [40 41]]

 [[50 51]
  [60 61]]]
1.18.5
[[[10 11]
  [20 21]
  [30 31]]

 [[40 41]
  [50 51]
  [60 61]]]


In [4]:
# Extract value from the array
ar4=np.array(["Atlas","Ascend","Mindspore","CNN"])
# Extract the second value
print(ar4[1])
# extract the values from No. 2 to the last
print(ar4[1:])
# extract the values from N0. 2 to the fourth but excluding the fourth.
print(ar4[1:3])
ar5=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14])
# extract all values with a step of 2
print(ar5[::2])
# extract all values with a step of 3
print(ar5[::3])

# Slicing 2-D arrays
ar6=np.array([["Mindspore","Atlas","Ascend","CNN"],["Tensorflow","Pytorch","Mindspore","Theano"]])
# print(ar6[second element,from index 0 to 2])
print(ar6[1,0:2])
print(ar6[0,1:3])
# print(ar6[from index 0 to 2, pick up index 1])
print(ar6[0:2,1])


Ascend
['Ascend' 'Mindspore' 'CNN']
['Ascend' 'Mindspore']
[ 1  3  5  7  9 11 13]
[ 1  4  7 10 13]
['Tensorflow' 'Pytorch']
['Atlas' 'Ascend']
['Atlas' 'Pytorch']


# Numpy Data Types
Create data types with Numpy
dtype for integer(i), string(S), float(f) , boolean(b), datetime(M), complex float(c), etc

In [5]:
import numpy as np
arr=np.array([1,2,3,4,5],dtype="i")
print(arr)
print(type(arr))
print(arr.dtype)
arr=np.array([1,2,3,4,5],dtype="f")
print(arr)
print(arr.dtype)
arr=np.array([1,2,3,4,5],dtype="i8")
print(arr.dtype)
print(arr)




[1 2 3 4 5]
<class 'numpy.ndarray'>
int32
[1. 2. 3. 4. 5.]
float32
int64
[1 2 3 4 5]


In [6]:
# Change the data type from float to integer
arr=np.array([1.2,1.8,2.4,2.9,3.1,4.8,5.1,5.9])
print(arr.dtype)
conarr=arr.astype(int)
print(conarr)
print(conarr.dtype)

float64
[1 1 2 2 3 4 5 5]
int64


# Check the shape of dimensional array

In [7]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
e = np.array([[[10,11],[20,21]],[[30,31],[40,41]],[[50,51],[60,61]]])
f = np.array([[[10,11],[20,21],[30,31]],[[40,41],[50,51],[60,61]]])
print("No. of dimension for a:",a.ndim)
print("Shape for a:",a.shape)
print("No. of dimension for b:",b.ndim)
print("Shape for b:",b.shape)
print("No. of dimension for c:",c.ndim)
print("Shape for c:",c.shape)
print("No. of dimension for d:",d.ndim)
print("Shape for d:",d.shape)
print("No. of dimension for e:",e.ndim)
print("Shape for e:",e.shape)
print("No. of dimension for f:",f.ndim)
print("Shape for f:",f.shape)

No. of dimension for a: 0
Shape for a: ()
No. of dimension for b: 1
Shape for b: (5,)
No. of dimension for c: 2
Shape for c: (2, 3)
No. of dimension for d: 3
Shape for d: (2, 2, 3)
No. of dimension for e: 3
Shape for e: (3, 2, 2)
No. of dimension for f: 3
Shape for f: (2, 3, 2)


In [8]:
# Creating Numpy Arrays
arr=np.array([1,2,3],ndmin=5)
print(arr)
print("shape of array:",arr.shape)
# it will create a 5 dimensions using a vector with values 1,2,3 and the last dimension has 3 values.

arr2=np.array([[1,2,3],[4,5,6]])
print(arr2)
print("Shape of array:",arr2.shape)
# generate 2 dimensions with three elements inside each

[[[[[1 2 3]]]]]
shape of array: (1, 1, 1, 1, 3)
[[1 2 3]
 [4 5 6]]
Shape of array: (2, 3)


# Array Reshaping
changing the shape of an array
by reshaping the array, we can add or remove dimensions or change the number of elements in each dimension.


In [9]:
# Changing from 1-D to multi-D
arr1d=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(arr1d)
print(arr1d.shape)
arr2d=arr1d.reshape(2,6)
print(arr2d)
arr6d=arr1d.reshape(6,2)
print(arr6d)



[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
